- name: Ensure docke volume mapping host directories exist
  become: true
  file:
    state: directory
    path: "{{ item | regex_replace('^(?P<host>.+):(?P<container>.+):(?P<mode>.+)', '\\g<host>') }}"
  with_items:
    - "{{ docker_elasticsearch_directory_volumes }}"
  tags:
    - install
    - upgrade


- name: Ensure docker volume mapping host file directories exist
  become: true
  file:
    state: directory
    path: "{{ item | regex_replace('^(?P<host>.+):(?P<container>.+):(?P<mode>.+)', '\\g<host>') | dirname }}"
  with_items:
    - "{{ docker_elasticsearch_file_volumes }}"
  tags:
    - install
    - upgrade

- name: Copy docker volume mapping host file
  become: true
  template:
    src="{{ docker_elasticsearch_template_path }}{{ item | regex_replace('^(?P<host>.+):(?P<container>.+):(?P<mode>.+)', '\\g<host>') | basename }}.j2"
    dest="{{ item | regex_replace('^(?P<host>.+):(?P<container>.+):(?P<mode>.+)', '\\g<host>') }}"
    mode='0644'
  with_items:
    - "{{ docker_elasticsearch_file_volumes }}"
  tags:
    - install
    - upgrade
    

- name: Remove existing {{ docker_elasticsearch_name }} container
  docker:
    docker_api_version: "{{ docker_api_version }}"
    image: "{{ docker_elasticsearch_image }}"
    name: "{{ docker_elasticsearch_name }}"
    state: absent
  tags:
    - install
    - upgrade

- name: Run docker elasticsearch container
  become: true
  docker:
    docker_api_version: "{{ docker_api_version }}"
    env: "{{ docker_elasticsearch_env }}"
    expose: "{{ docker_elasticsearch_expose }}"
    image: "{{ docker_elasticsearch_image }}"
    name: "{{ docker_elasticsearch_name }}"
    ports: "{{ docker_elasticsearch_ports }}"
    links: "{{ docker_elasticsearch_links }}"
    memory_limit: "{{ docker_elasticsearch_memory_limit }}"
    volumes: "{{ docker_elasticsearch_volumes }}"
    log_driver: "{{ docker_elasticsearch_log_driver }}"
    log_opt: "{{ docker_elasticsearch_log_opt }}"
    pull: always
    restart_policy: always
    state: reloaded
  tags:
    - install
    - upgrade
